#!/bin/bash -exu

HEREDIR=`dirname $0`
cd "$HEREDIR"
HEREDIR=`pwd`

"$HEREDIR/build"

ROOTDIR="$HEREDIR/.."
cd "$ROOTDIR"
ROOTDIR=`pwd`

stack upload --stack-yaml ./stack.yaml .

PKG_NAME=`cabalish name`
PKG_VERSION=`cabalish version`

dist=`stack path --dist-dir --stack-yaml ./stack.yaml 2> /dev/null`

echo -e "\033[1;36mGenerating documentation...\033[0m"
stack haddock 2> /dev/null

if [ "$?" -eq "0" ]; then
  docdir=$dist/doc/html
  cd $docdir
  doc="${PKG_NAME}-${PKG_VERSION}-docs"
  echo -e "Compressing documentation from \033[1;34m$docdir\033[0m for \033[1;35m$PKG_NAME\033[0m-\033[1;33m$PKG_VERSION\033[1;30m"
  cp -r $PKG_NAME $doc
  tar -c -v -z --format=ustar -f $doc.tar.gz $doc
  echo -e "\033[1;32mUploading to Hackage...\033[0m"
  read -p "Hackage username: " username
  read -p "Hackage password: " -s password
  echo ""
  set +x
  curl -X PUT -H 'Content-Type: application/x-tar' -H 'Content-Encoding: gzip' --data-binary "@$doc.tar.gz" "https://$username:$password@hackage.haskell.org/package/${PKG_NAME}-${PKG_VERSION}/docs"
else
  echo -e "\033[1;31mNot in a stack-powered project\033[0m"
fi
